### ISSUE TITLE
[question] Why include both tailwind vs. styled-components?

### ISSUE THREAD

**Issue by maxichrome** [cnrad/next-template#2]
Which cases would you use one over the other in the same app, and why you find pre-including both libraries to be useful?

Not challenging the decision, I'm just curious!

**Comment by cnrad** [comment]
Use-case, really.

If what I'm making isn't a super expansive web app, and I just need a few simple pages, I like having the freedom of styled-components to work with and really customize, but if it's a bigger project, Tailwind is easier for me to work with and keep things consistent and concise with. 

I pre-include both of them because if I only want to use one, I find it's much easier to remove it than to install and configure it (mainly Tailwind), and I like the choice to start off with.
